import { z } from 'zod';
import { baseEnvSchema, envBool, envPort, loadEnv } from '@cip/observability';

export const apiEnvSchema = baseEnvSchema.extend({
  API_PORT: envPort.default(4100),
  API_HOST: z.string().default('127.0.0.1'),
  DATABASE_URL: z.string().url().default('postgres://app_user@127.0.0.1:5432/cip'),
  DATABASE_SYSTEM_URL: z.string().url().default('postgres://app_system@127.0.0.1:5432/cip'),
  DATABASE_ADMIN_URL: z.string().url().default('postgres://127.0.0.1:5432/cip'),
  DATABASE_POOL_SIZE: z.coerce.number().int().min(1).max(200).default(20),
  MIGRATE_ON_START: envBool.default(false),
  REDIS_URL: z.string().default('redis://127.0.0.1:6379/1'),
  REDIS_PREFIX: z.string().default(''),
  RABBITMQ_URL: z.string().default('amqp://guest:guest@127.0.0.1:5672/cip'),
  CLICKHOUSE_URL: z.string().url().default('http://127.0.0.1:8123'),
  CLICKHOUSE_DATABASE: z.string().default('cip'),
  S3_ENDPOINT: z.string().url().default('http://127.0.0.1:9002'),
  S3_PUBLIC_URL: z.string().url().default('http://127.0.0.1:9002'),
  S3_REGION: z.string().default('us-east-1'),
  S3_BUCKET: z.string().default('cip'),
  S3_ACCESS_KEY: z.string().default('minioadmin'),
  S3_SECRET_KEY: z.string().default('minioadmin'),
  S3_KEY_PREFIX: z.string().default(''),
  SMTP_HOST: z.string().default('127.0.0.1'),
  SMTP_PORT: z.coerce.number().int().default(1025),
  MAIL_FROM: z.string().default('Commerce Intelligence <no-reply@cip.local>'),
  JWT_SECRET: z.string().min(16).default('dev-only-change-me-please-32-chars'),
  ACCESS_TOKEN_TTL_SECONDS: z.coerce.number().int().min(30).default(900),
  REFRESH_TOKEN_TTL_DAYS: z.coerce.number().int().min(1).default(30),
  COOKIE_SECURE: envBool.default(false),
  PAYMENT_PROVIDER: z.enum(['fake', 'stripe']).default('fake'),
  FAKE_PAYMENT_WEBHOOK_SECRET: z.string().min(8).default('whsec_fake_local_secret'),
  FAKE_PAYMENT_DELAY_MS: z.coerce.number().int().min(0).default(2000),
  FAKE_PAYMENT_POLL_MS: z.coerce.number().int().min(0).default(1000),
  STRIPE_SECRET_KEY: z.string().optional(),
  STRIPE_WEBHOOK_SECRET: z.string().optional(),
  INTERNAL_API_URL: z.string().url().default('http://127.0.0.1:4100'),
  ADMIN_URL: z.string().url().default('http://127.0.0.1:4140'),
  STOREFRONT_REVALIDATE_URL: z.string().url().optional(),
  REVALIDATE_SECRET: z.string().default('dev-revalidate-secret'),
  REALTIME_PUBLIC_URL: z.string().default('ws://127.0.0.1:4120/ws'),
  COLLECTOR_PUBLIC_URL: z.string().default('http://127.0.0.1:4110'),
  STOREFRONT_RATE_LIMIT_PER_MIN: z.coerce.number().int().min(1).default(300),
  LOGIN_RATE_LIMIT: z.coerce.number().int().min(1).default(5),
  RESERVATION_TTL_MINUTES: z.coerce.number().int().min(1).default(15),
  ANALYTICS_CACHE_SECONDS: z.coerce.number().int().min(0).default(30),
  CONSUMERS_ENABLED: envBool.default(true),
  JOBS_ENABLED: envBool.default(true),
  LLM_PROVIDER: z.enum(['fake', 'anthropic', 'openai']).default('fake'),
  LLM_MODEL: z.string().optional(),
  LLM_API_KEY: z.string().optional(),
  LLM_BASE_URL: z.string().optional(),
  LLM_TIMEOUT_MS: z.coerce.number().int().min(1000).default(60000),
  LLM_PRICE_INPUT_PER_MTOK: z.coerce.number().min(0).optional(),
  LLM_PRICE_OUTPUT_PER_MTOK: z.coerce.number().min(0).optional(),
  LLM_FAKE_LATENCY_MS: z.coerce.number().int().min(0).default(0),
  LLM_FAKE_INVALID_FIRST: z.coerce.number().int().min(0).default(0),
  DECISION_CACHE_MS: z.coerce.number().int().min(0).default(2000),
  LLM_DAILY_LIMIT: z.coerce.number().int().min(0).default(50),
  LLM_CACHE_TTL_SECONDS: z.coerce
    .number()
    .int()
    .min(0)
    .default(30 * 86400),
  EMBEDDINGS_PROVIDER: z.enum(['hash', 'local', 'openai', 'voyage']).default('hash'),
  EMBEDDINGS_MODEL: z.string().optional(),
  EMBEDDINGS_URL: z.string().optional(),
  EMBEDDINGS_API_KEY: z.string().optional(),
  EMBEDDINGS_VERSION: z.string().optional(),
  FLAGS_RELAY_URL: z.string().optional(),
  FLAGS_SDK_KEY: z.string().optional(),
  AI_CREATIVES_DEFAULT: envBool.default(true),
  BANDIT_DISCOUNT: z.coerce.number().min(0.5).max(1).default(1),
  BANDIT_WARMUP: z.coerce.number().int().min(0).default(50),
  HOLDOUT_PERCENT: z.coerce.number().int().min(0).max(50).default(10),
  RECO_CACHE_SECONDS: z.coerce.number().int().min(0).default(300),
  PROFILE_SNAPSHOT_INTERVAL_MS: z.coerce.number().int().min(1000).default(600_000),
  BANDIT_SNAPSHOT_INTERVAL_MS: z.coerce.number().int().min(1000).default(300_000),
  VIP_REFRESH_INTERVAL_MS: z.coerce.number().int().min(1000).default(86_400_000),
  INSIGHTS_CACHE_SECONDS: z.coerce.number().int().min(0).default(3600),
  IMPORT_MAX_ROWS: z.coerce.number().int().min(1).default(5000),
});

export type ApiConfig = z.infer<typeof apiEnvSchema>;

export function loadConfig(env: Record<string, string | undefined> = process.env): ApiConfig {
  return loadEnv(apiEnvSchema, env);
}
