apiVersion: 1
deleteDatasources:
  - name: Tempo
    orgId: 1
  - name: Loki
    orgId: 1
datasources:
  - name: Prometheus
    uid: prometheus
    type: prometheus
    access: proxy
    url: ${CIP_PROMETHEUS_URL}
    isDefault: true
    jsonData:
      timeInterval: 5s
      httpMethod: POST
  - name: Jaeger
    uid: jaeger
    type: jaeger
    access: proxy
    url: ${CIP_JAEGER_URL}
    jsonData:
      tracesToMetrics:
        datasourceUid: prometheus
        spanStartTimeShift: '-5m'
        spanEndTimeShift: '5m'
        tags:
          - key: service.name
            value: service
        queries:
          - name: Request rate
            query: 'sum(rate(http_requests_total{$$__tags}[1m]))'
